from mtg_creatures import *
from mtg_land import *
from mtg_enchant import *
from mtg_instant import *
from mtg_artifact import *
from mtg_sorcery import *


one_of_everything={
    AnkhOfMishra:1,
    WoodenSphere:1,
    CrystalRod:1,
    IronStar:1,
    IvoryCup:1,
    ThroneOfBone:1,
    SoulNet:1,
    SolRing:1,
    LibraryOfLeng:1,
    HowlingMine:1,
    BlackLotus:1,
    MoxEmerald:1,
    MoxRuby:1,
    MoxJet:1,
    MoxPearl:1,
    MoxSapphire:1,
    SavannahLions:1,
    SerraAngel:1,
    ScatheZombies:1,
    AirElemental:1,
    ProdigalSorcerer:1,
    WhiteKnight:1,
    BlackKnight:1,
    TundraWolves:1,
    BenalishHero:1,
    BirdsOfParadise:1,
    BogWraith:1,
    Cockatrice:1,
    CrawWurm:1,
    DragonWhelp:1,
    DrudgeSkeletons:1,
    EarthElemental:1,
    ElvishArchers:1,
    FireElemental:1,
    Fungusaur:1,
    GiantSpider:1,
    GrayOgre:1,
    GrizzlyBears:1,
    HillGiant:1,
    HurloonMinotaur:1,
    IronclawOrcs:1,
    IronrootTreefolk:1,
    LlanowarElves:1,
    MahamotiDjinn:1,
    MerfolkOfThePearlTrident:1,
    MesaPegasus:1,
    MonsGoblinRaiders:1,
    ObsianusGolem:1,
    OrcishArtillery:1,
    PearledUnicorn:1,
    PhantomMonster:1,
    RocOfKherRidges:1,
    ScrybSprites:1,
    ShanodinDryads:1,
    ThicketBasilisk:1,
    TimberWolves:1,
    VerduranEnchantress:1,
    WallOfAir:1,
    WallOfIce:1,
    WallOfStone:1,
    WallOfSwords:1,
    WallOfWood:1,
    WaterElemental:1,
    WildGrowth:1,
    Fastbond:1,
    Lifetap:1,
    ManaFlare:1,
    ManaBarbs:1,
    Pestilence:1,
    HolyStrength:1,
    AspectOfWolf:1,
    BadMoon:1,
    Crusade:1,
    LandTax:1,
    Counterspell:1,
    AncestralRecall:1,
    LightningBolt:1,
    Disenchant:1,
    SwordsToPlowshares:1,
    Plains:1,
    Mountain:1,
    Island:1,
    Forest:1,
    Swamp:1,
    Badlands:1,
    Bayou:1,
    Plateau:1,
    Savannah:1,
    Scrubland:1,
    Taiga:1,
    TropicalIsland:1,
    Tundra:1,
    UndergroundSea:1,
    VolcanicIsland:1,
    Armageddon:1,
    WrathOfGod:1,
    Disintegrate:1,
    }


basic_white={
    Crusade:4,
    SerraAngel:4,
    SavannahLions:4,
    WhiteKnight:4,
    Disenchant:4,
    SwordsToPlowshares:4,
    LandTax:2,
    TundraWolves:4,
    BlackLotus:1,
    MoxPearl:1,
    Plains:10,
    }

enchantress = {
    Cockatrice:2,
    ElvishArchers:4,
    LlanowarElves:4,
    ThicketBasilisk:4,
    VerduranEnchantress:4,
    Forest:24,
    Fastbond:1,
    AspectOfWolf:2,
    #Regeneration:2,
    #LivingArtifact:3,
    #Lure:4,
    WildGrowth:4,
    #JayemdaeTome:2,
    }

white_aggro = {
    #NorthernPaladin:2,
    SerraAngel:2,
    BenalishHero:4,
    MesaPegasus:4,
    SavannahLions:4,
    WhiteKnight:4,
    Disenchant:2,
    SwordsToPlowshares:4,
    Armageddon:4,
    Crusade:4,
    Plains:26,
    }





test = {
    DrudgeSkeletons:20,
    }
